language: python
python:
  - "2.7.15"
# command to install dependencies

before_install:
  - sudo apt-get update
  - export PYTHONPATH=$PYTHONPATH:$(pwd)


install:
  # install requirements of physcraper
  - pip install --force-reinstall numpy==1.14.5
  - pip install -r requirements.txt
  - pip install configparser
  - python setup.py install
  
  
  ### install blast+
  # this fails often with connection errors
  #- sudo apt-get install ncbi-blast+
  #- sudo apt-get install muscle


  #### install papara
  #- wget 'https://sco.h-its.org/exelixis/resource/download/software/papara_nt-2.5-static_x86_64.tar.gz'
  #- gunzip  -cd papara_nt-2.5-static_x86_64.tar.gz | (tar xvf - )
  #- mv papara_static_x86_64 papara
  #- export PATH="$PATH:$(pwd)"
  #- papara

  ##### to use RAXML we need conda
 # - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
 # - chmod +x miniconda.sh
 # - bash miniconda.sh -b -p $HOME/miniconda
 # - export PATH="$HOME/miniconda/bin:$PATH"
 # - conda config --set always_yes yes --set changeps1 no
 # - conda update -q conda
 # - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
 # - source activate test-environment
  #- conda install -c bioconda raxml 


  #### ete fails now, because of conda
 # - conda install -c etetoolkit ete2
 # - export PATH=~/anaconda_ete/bin:$PATH

  #### check build documentation with sphinx
 # - pip install sphinx
 # - make -C docs

  #### needed for mpi4py which is in requirements
  #- sudo apt install libopenmpi-dev
  #- sudo apt install mpich
  #- export MPICC=mpiicc
  
# command to run tests
script:
  #- wget 'https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdump.tar.gz'
  #- gunzip  -cd taxdump.tar.gz | (tar xvf - names.dmp nodes.dmp)
  #- mv *.dmp taxonomy/
  - echo 'no' | python tests/testfilesetup.py
  #- py.test tests/ --setup-only
  - sh tests/run_tests.sh

after_success:
  - curl -s https://codecov.io/bash | bash

